version: '3.7'

services:
    web:
        user: "app:app"
        build: ./web    
        command: gunicorn qrcertificate.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ../:/usr/src/app/
        expose:
            - 8000
        env_file:
            - ../.env.prod
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - ../:/usr/src/app/
        depends_on:
            - web
