# Generated by Django 4.0.6 on 2022-07-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name In Arabic')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name In English')),
                ('national_id', models.IntegerField(blank=True, null=True, verbose_name='National Identification Number')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('receipt_no', models.IntegerField(blank=True, null=True, verbose_name='Receipt Number')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Receipt Issued Time')),
                ('cert_no', models.CharField(max_length=40, unique=True, verbose_name='Certification Number')),
                ('course_ar', models.CharField(max_length=100, verbose_name='Course In Arabic')),
                ('course_en', models.CharField(max_length=100, verbose_name='Course In English')),
                ('issuer_ar', models.CharField(max_length=100, verbose_name='Issuer Name In Arabic')),
                ('issuer_en', models.CharField(max_length=100, verbose_name='Issuer Name In English')),
                ('course_start', models.DateTimeField(verbose_name='Course Started Time')),
                ('course_end', models.DateTimeField(verbose_name='Course Ended Time')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Certification Issued Time')),
            ],
        ),
    ]
